### ISSUE TITLE
Unimplemented ext2 library function while setting up superblock

### ISSUE THREAD

**Issue by svenha** [Intrinsically-Sublime/fajita-factory-flash-bash-scripts#1]
I am using the flash-all.sh on Ubuntu 21.04, but it stops as follows.

    bash -x flash-all.sh
    + echo 'To reflash one slot without losing data on the other slot skip wiping data and skip flashing '\''persist'\''.'
    To reflash one slot without losing data on the other slot skip wiping data and skip flashing 'persist'.
    + echo ''
    + read -p 'Do you want to wipe all the data ( recommended )[Y/N]?' -n 1 -r
    Do you want to wipe all the data ( recommended )[Y/N]?y+ echo
    + [[ y =~ ^[Yy]$ ]]
    + echo ''
    + echo '** If wiping data fails but the install is successful ignore the error **'
    ** If wiping data fails but the install is successful ignore the error **
    + echo '** If the install fails please boot into TWRP and use Wipe/Format first **'
    ** If the install fails please boot into TWRP and use Wipe/Format first **
    + echo ''
    + sudo fastboot -w
    Erasing 'userdata'                                 OKAY [  1.205s]
    mke2fs 1.45.7 (28-Jan-2021)
    /tmp/TemporaryFile-sPn0OL: Unimplemented ext2 library function while setting up superblock
    /usr/lib/android-sdk/platform-tools/mke2fs failed with status 1
    fastboot: error: Cannot generate image for userdata
    + read -p 'Do you want to flash the system '\''a'\'' partitions [Y/N]?' -n 1 -r

**Comment by Intrinsically-Sublime** [comment]
This seems to be fairly common and you do not always need to wipe the data. I would first try skipping the step and if that does not work you can boot into TWRP and wipe the userdata and cache from there. After that just skip the step while running flashall.sh.

**Comment by svenha** [comment]
OK, I skipped the step and it proceeded further till the transfer of little files when in TWRP mode. But then the device showed "QUALCOMM CrashDump Mode". What to do now?

**Comment by Intrinsically-Sublime** [comment]
You can hold down all three buttons until it restarts. If you keep holding them down it should start into Fastboot mode. Be sure the USB cable is NOT plugged in. If it is plugged in during reboot it will boot into EDL mode (Emergency download). If it gets stuck on a black screen and will not reboot after holding all three buttons for a long time it is in EDL mode. EDL is used to flash stock firmware with Qualcomms tool via windows.

Worse case scenario is you brick it and have to use the EDL mode and Windows tool to reflash. I had to use it once and have since used the flashall script to reflash a few times as well while playing with UT and postmarketos.

Here is a guide and the downloads for EDL. https://www.thecustomdroid.com/oneplus-6-6t-unbrick-guide/

I had to borrow a computer to use Windows myself as W7 in virtualbox did not work.

**Comment by Intrinsically-Sublime** [comment]
I should say if it reboots into fastboot then you should just try again.
